experiment_name:  "ettm2_96_lr1e4_10epochs"
seed: 3097
dataset: "ETTm2"
data_path: "data/raw/ETTm2.csv"
features: "M"                     # "M" = multivariate forecasting
target: "OT"                      # target column
results_dir: "results/ettm2_96_lr1e4_10epochs"
seq_len: 96                       # input length given to the encoder
label_len: 48                     # known past part given to the decoder
pred_len: 96                      # forecasting horizon
model: "Autoformer"
d_model: 512                      # internal model dimension
n_heads: 8                        # number of Auto-Correlation heads
enc_layers: 2
dec_layers: 1
d_ff: 2048                        # hidden dimension of feed-forward layers in the encoder and decoder
dropout: 0.05                     # dropout used in embedding and model blocks
moving_avg: 25                    # moving average window used in SeriesDecomp
c: 1                              # factor c used for top-k delays in Auto-Correlation
activation: "gelu"
enc_in: 7
dec_in: 7
c_out: 7
embed: "timeF"                    # values: "timeF" = time features embedding
freq: "t"                         # frequency for time features encoding, "t" = minutely frequency, "h" = hourly frequency
batch_size: 32
learning_rate: 0.0001
epochs: 10
patience: 3                       # early stopping patience
lradj: "type1"                    # learning rate adjustment strategy
checkpoint_dir: "checkpoints/ettm2_96_lr1e4_10epochs"
use_mps: true
use_cuda: true
use_cpu: true
wandb_enabled: true               # enable W&B logging, true = log metrics to W&B, false = no logging
wandb_project: "autoformer-from-scratch"
wandb_run_name: "ettm2_96"
