# =============================
# Experiment
# =============================

experiment_name: "weather_192_lr1e4_10epochs"
seed: 3097


# =============================
# Dataset
# =============================

dataset: "Weather"                                   # dataset used for the first debug experiment
data_path: "data/raw/weather/weather.csv"        # path to the raw csv file

features: "M"                          # "M" = multivariate forecasting
target: "OT"                           # target column used in ETT datasets
results_dir: "results/weather_192_lr1e4_10epochs"       # directory where to save results


# =============================
# Sequence lengths
# =============================

seq_len: 96                            # input length given to the encoder
label_len: 48                          # known past part given to the decoder
pred_len: 192                          # forecasting horizon

# Decoder length is not written directly in the config.
# It will be computed in the code as:
# dec_len = label_len + pred_len


# =============================
# Model: Autoformer
# =============================

model: "Autoformer"                    # model name

d_model: 512                           # internal model dimension
n_heads: 8                             # number of Auto-Correlation heads
enc_layers: 2                          # number of encoder layers
dec_layers: 1                          # number of decoder layers
d_ff: 2048                             # hidden dimension of feed-forward layers
dropout: 0.05                          # dropout used in embedding and model blocks

moving_avg: 25                         # moving average window used in SeriesDecomp
c: 3                                   # factor c used for top-k delays in Auto-Correlation

activation: "gelu"

# =============================
# Input / output dimensions
# =============================

enc_in: 21                              # number of input variables for the encoder
dec_in: 21                            # number of input variables for the decoder
c_out: 21                             # number of output variables


# =============================
# Embedding
# =============================

embed: "timeF"                         # use numerical time features
freq: "t"                              # time frequency: "t" = minutely/15-min features for ETTm2, other datasets are used to use "h" = hourly features


# =============================
# Training
# =============================

batch_size: 32                         # number of samples per batch
learning_rate: 0.0001                 # optimizer learning rate, lr = 1e-4 official
epochs: 10                             # maximum number of training epochs
patience: 3                            # early stopping patience
lradj: "type1"                         # learning rate adjustment strategy

use_grad_clip: false                    # whether to use gradient clipping
grad_clip: 1.0                         # maximum norm for gradient clipping

checkpoint_dir: "checkpoints/weather_192_lr1e4_10epochs" # directory where to save best model checkpoint


# =============================
# Device
# =============================

use_mps: true                          # use Apple Silicon GPU if available
use_cuda: true                         # use CUDA GPU if available
use_cpu: true                          # fallback to CPU if no GPU backend is available


# =============================
# Weights & Biases
# =============================

wandb_enabled: true                    # enable W&B logging, true = log metrics to W&B, false = no logging
wandb_project: "autoformer-from-scratch"
wandb_run_name: "weather_192"